global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using BinaryStars.Models;
global using BinaryStars.Presentation;
global using BinaryStars.Services.Endpoints;
global using BinaryStars.DataContracts;
global using BinaryStars.DataContracts.Serialization;
global using BinaryStars.Services.Caching;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
